# Generated by Django 4.2.7 on 2023-12-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=15)),
                ('course_name', models.CharField(max_length=40)),
                ('course_credit', models.DecimalField(decimal_places=1, max_digits=4)),
                ('tutorial_full_marks', models.DecimalField(decimal_places=2, max_digits=4)),
                ('att_full_marks', models.DecimalField(decimal_places=2, max_digits=4)),
                ('final_full_marks', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
